### ISSUE TITLE
Paginate blog page

### ISSUE THREAD

**Issue by ShweataNHegde** [TylerMRoderick/fernfolio-11ty-template#8]
Hi Tyler, 

Thanks for creating this template. While setting up my portfolio using your template, I realised that the blog page doesn't have pagination. I'm new to Eleventy and couldn't immediately figure out how to get pagination to work. Any pointers would be great! 

Thanks!

**Comment by ShweataNHegde** [comment]
I tried playing around with Eleventy's pagination. 

I added this bit to the `pages/blog.md`'s front matter: 

```
pagination:
  data: collections.post
  size: 2
  alias: blog
permalink: "blog{% if pagination.pageNumber > 0 %}/page/{{ pagination.pageNumber }}{% endif %}/index.html"
```

I changed `{% for post in postslist | reverse %}` to `	{% for post in pagination.items | reverse %}` in `components/postlist.njk` and added the following code at the end. 

```
<div class="pagination">
      {% if pagination.href.previous %}
        <a class="page-link" href="{{pagination.href.previous}}">Previous</a>
      {% endif %}
      {% for pageEntry in pagination.hrefs %}
        <a class="page-link" href="{{ pageEntry }}">{{ loop.index }}</a>
      {% endfor %}
      {% if pagination.href.next %}
       <a class="page-link" href="{{pagination.href.next}}">Next</a>                        
      {% endif %}
</div>
```

I thought I had it working until I realized that I had broken tags in the process, and I can't understand how. This is what I get when I click on one of the tags. 

![tags page](https://user-images.githubusercontent.com/70576776/182035108-4b273aa8-42b9-4a1d-8513-3ca5bf9479d2.png)
